# -*- coding: utf-8 -*-
"""HW1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MfYF9BE3VIPGRDN_nwzsJla8JcxJQB-x
"""

print("Hello World")

print(4+4)